name: Build JAR

on:
  push:
    branches: [ "master" ]
    paths:
      - "src"
      - "build.sbt"
      - ".github/workflows/build.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: openjdk@1.17.0
    - name: Install SWI-Prolog backend
      run: sudo apt-add-repository -y ppa:swi-prolog/stable; sudo apt update; sudo apt install swi-prolog-java
    - name: build application
      run: sbt packageZip
    - uses: actions/upload-artifact@v4
      with:
        name: netprologo-1.0.0.zip
        path: netprologo-1.0.0.zip